Portfolio/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;
using Portfolio.Models;
using Microsoft.AspNetCore.Localization;
using System.Diagnostics;
using Briefcase.Models;

namespace Briefcase.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly ILogger<AboutMeController> _logger;

        public AboutMeController(ILogger<AboutMeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var profil = new Profil();
            return View(profil);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult CultureConnexion(string newCulture, string URL)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(newCulture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddHours(3) });

            return LocalRedirect(URL);
        }
    }
}

Portfolio/Controllers/SkillsController.cs
using Briefcase.Models;
using Microsoft.AspNetCore.Mvc;

namespace Briefcase.Controllers
{
    public class SkillsController : Controller
    {
        public IActionResult Index()
        {
            var programmingTechnologies = new ProgrammingTechnologies();
            return View(programmingTechnologies);
        }
    }
}

Portfolio/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@using Microsoft.AspNetCore.Mvc.Localization;

@inject IOptions<RequestLocalizationOptions> LocalizationOptions;

@inject IViewLocalizer watchResource;

@{
    var getCulture = Context.Features.Get<IRequestCultureFeature>();

    var culturesList = LocalizationOptions.Value.SupportedCultures.Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName }).ToList();

    var currentURL = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@watchResource["Briefcase"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portfolio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/aboutMe.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/contact.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/projects.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/skills.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/workExperiences.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a id="myName" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">William Alexander Hernandez</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div  id="menu"class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ">
                            <a class="nav-link " asp-area="" asp-controller="AboutMe" asp-action="Index">@watchResource["AboutMe"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Skills" asp-action="Index">@watchResource["Skills"]</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-controller="Home" asp-action="CultureConnexion" asp-route-URL="@currentURL">
                        <select name="newCulture"
                                asp-for="@getCulture.RequestCulture.UICulture.Name"
                                asp-items="culturesList"
                                onchange="this.form.submit()">
                        </select>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer">
        <div >
            &copy; 2024 - @watchResource["Profile"] William Alexander Hernandez - @watchResource["All rights reserved"]
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/aboutMe.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>